# Generated by Django 5.1.7 on 2025-05-23 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_article_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='read_time',
            field=models.IntegerField(),
        ),
    ]
